org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03
minecraft_version=1.20.1
forge_version=47.4.0

mod_version=0.1.1
mod_id=makeae2better
mod_name=Make AE2 Better
mod_url=https://github.com/qiuye2024github/MaekAE2Better
mod_authors=qiuye2024github
mod_description=Better AE2
mod_issue_tracker=https://github.com/qiuye2024github/MaekAE2Better/issues
mod_license=MIT
mod_group_id=cn.qiuye

mixinextras_version=0.2.0
jei_version=15.20.0.106

guideme_version=20.1.11
glodium_version=1.20-1.5
ae2_version=15.4.5
extendedae_version=1.20-1.4.2

sophisticated_core_version=1.2.73.1028
sophisticated_backpacks_version=3.23.22.1273